language: node_js
node_js:
  - 'lts/*'

cache:
  directories:
  - "$HOME/.npm"

matrix:
  include:
    - env: REACT_VERSION=^16
    - env: REACT_VERSION=

before_script:
  - if [[ $REACT_VERSION ]]; then
      npm install react@$REACT_VERSION react-dom@$REACT_VERSION;
    fi
script:
  - npm test
  - npm run build
